### ISSUE TITLE
Sentence is not defined

### ISSUE THREAD

**Issue by kamarasinghe** [learn-co-curriculum/skills-based-js-intro-to-variables#11]
function speaker() {
  sentence = 'Bird is the word.';
}
 
console.log(sentence);

I think the "}" should go after the console.log(sentence); because in Chrome's console it gives an error the way it is currently written.  Hope this helps, have a great day.

**Comment by sivaraam** [comment]
It's because the global variable inside the function seems to defined only after the function is first called. Try this,
```
function speaker() {
    sentence = 'Bird is the word.';
}
speaker();
console.log(sentence);
```
