### ISSUE TITLE
Trouble with example in browser console

### ISSUE THREAD

**Issue by priscilla-littlecat** [learn-co-curriculum/skills-based-js-intro-to-variables#14]
Hello,

When I typed in the first example in my browser's console, and typed in "console.log(speaker)", I did not get "Bird is the word."  Rather, the console printed out the whole code.  I know I typed the code exactly as it appeared in the lesson.  Am I overlooking a syntax error?

**Comment by sivaraam** [comment]
I guess you should see #11, if you still seem to having the issue.
