### ISSUE TITLE
You Don't Know JS - Function vs. Block Scope link dead D;

### ISSUE THREAD

**Issue by joshycsm** [learn-co-curriculum/skills-based-js-intro-to-variables#19]
replace with link below?

https://medium.com/@josephcardillo/the-difference-between-function-and-block-scope-in-javascript-4296b2322abe

:)

**Comment by maxwellbenton** [comment]
Hi @joshycsm,

Thank you for catching this and providing feedback. We've replaced the dead link with the resource you provided, which should resolve this issue.

Thank you for contributing to this lesson!
